require("impatient")

require("core.settings")
require("core.mappings")
require("core.plugins")

require("plugins.lualine")
require("plugins.tokyonight")
require("plugins.barbar")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.whichkey")

require("plugins.mason")
require("plugins.lspconfig")
require("plugins.completion")
require("plugins.lspsaga")
require("plugins.null")
