local s = vim.opt

s.backup                  = false
s.clipboard               = "unnamedplus"
s.cmdheight               = 0
s.completeopt             = { "menuone", "noselect" }
s.conceallevel            = 0
s.fileencoding            = "utf-8"
s.hlsearch                = true
s.incsearch               = true
s.ignorecase              = true
s.smartcase               = true
s.mouse                   = "a"
s.pumheight               = 10
s.showmode                = false
s.showtabline             = 2
s.smartindent             = true
s.splitbelow              = true
s.splitright              = true
s.swapfile                = false
s.termguicolors           = true
s.timeoutlen              = 1000
s.undofile                = true
s.updatetime              = 300
s.writebackup             = false
s.expandtab               = true
s.shiftwidth              = 2
s.tabstop                 = 2
s.cursorline              = true
s.number                  = true
s.numberwidth             = 4
s.signcolumn              = "yes"
s.wrap                    = false
s.scrolloff               = 8
s.sidescrolloff           = 8
s.background              = "dark"
s.backspace               = "indent,eol,start"
